version: "3.7"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/loki/loki-config.yaml
      - ./loki-data:/loki:rw
    command: -config.file=/loki/loki-config.yaml
    networks:
      - grafana-stack
    environment:
      - LOG_LEVEL=debug
    user: "0:0"  # Run as current host user to avoid permission issues


  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log:rw
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on: 
      - loki
    networks:
      - grafana-stack

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana:rw 
      - ./grafana-provisioning:/etc/grafana/provisioning:rw
   
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    networks:
      -  grafana-stack

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./gen-targets.sh:/gen-targets.sh
    ports:
      - "9090:9090"
    networks:
      -  grafana-stack
    env_file:
      - .env
    environment:
      - METRICS_TARGET=${METRICS_TARGET}
    entrypoint: /bin/sh -c "/gen-targets.sh && prometheus --config.file=/etc/prometheus/prometheus.yml"

networks:
  grafana-stack:
    driver: bridge