auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  chunk_idle_period: 3m
  chunk_block_size: 262144
  max_chunk_age: 1h
  flush_check_period: 1s

storage_config:
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2024-04-01
      object_store: filesystem
      store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/compactor

limits_config:
  max_streams_per_user: 1000000
  max_global_streams_per_user: 1000000