global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet-app'
    scrape_interval: 5s
    scheme: http
    tls_config:
      insecure_skip_verify: true  # Skips SSL verification (useful for self-signed certificates)
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
